config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :registration, only: %i[new create]
  resources :passwords, param: :token
  resources :messages
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "sessions#new"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy]

  # GET /messages or /messages.json
  def index
    if params[:room_id]
      @room = Room.find(params[:room_id])
      @messages = @room.messages.includes(:user)
    else
      @messages = []
    end
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id = session[:user_id]

    respond_to do |format|
      if @message.save
        @message.broadcast_append_to @message.room, partial: @message, locals: { message: @message }, target: "message-list"
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    respond_to do |format|
      @message.broadcast_remove_to @message.room, target: @message
      format.html { redirect_to messages_path, status: :see_other, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :room_id, :user_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<div id='message-actions'>
  <%= form_with(model: message, id: 'message-form') do |form| %>
    <div class='input-container'>
      <%= form.text_field :content, class: 'full-width'%>
      <%= form.hidden_field :room_id %>
      <%= form.hidden_field :user_id %>
      <%= form.submit 'Send',class: 'send-button' %>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" class="message">
    <div id='sender'>
        <p id='email'><%= message.user.email_address %></p>
        <p id='time'><%= message.created_at %></p>
    </div>
    <h3>
        <%= message.content %>
        <% if session[:user_id] == message.user_id %> 
            <%= button_to 'Delete', message, method: :delete, class: 'delete' %>
            <%# <%= button_to 'Delete', message, method: :delete, data: { turbo_action: 'replace', turbo_confirm: 'Are you sure?' } %>
        <% end %>
    </h3>
</div>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "message-list", partial: "message", object: @message %>
<%= turbo_stream.replace "message-actions", partial: "form", locals: {message:Message.new(room: @message.room)} %>

app/views/messages/destoy.turbo_stream.erb
<%= turbo_stream.remove @message %>

app/views/messages/edit.html.erb
<% content_for :title, "Editing message" %>

<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Messages" %>

<h1>Messages</h1>

<div id='messages'>
 <%= turbo_frame_tag 'room-messages' do %>
  <div id='message-list'>
    <% @messages.each do |message| %>
    <%= render message %>
    <% end %>
  </div>
  <%= render partial: 'messages/form', locals: {message: Message.new(room: @room)} %>

  <%= turbo_stream_from @room %>
 <% end %>
</div>

app/views/messages/new.html.erb
<% content_for :title, "New message" %>

<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>