config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :registration, only: %i[new create]
  resources :passwords, param: :token
  resources :messages
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "sessions#new"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  allow_unauthenticated_access
  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
    @room = @rooms[0] unless @rooms.empty?
    @messages = []
    @messages = @room.messages unless @rooms.empty?
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        @room.broadcast_append_to @room.name, partial: @room, locals: { room: @room }, target: "room-list"
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_path, status: :see_other, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div id='actions'>  
  <%= form_with(model: room) do |form| %>
    <% if room.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

        <ul>
          <% room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div id='create-room-container'>
      <%= form.label :name, "Room Name", class: "form-label" %>
      <%= form.text_field :name, class: "form-input" %>
      <%= form.submit class: 'create-room' %>
    </div>
  <% end %>
</div>

app/views/rooms/_room.html.erb
<%= link_to messages_path(room_id: room.id), data: { turbo_frame: 'room-messages' }, class: 'room-button' do %>
  <div class='room'>
    <%= room.name %>
  </div>
<% end %>

app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.append "room-list", partial: "room", object: @room %>
<%= turbo_stream.replace "actions", partial: "form", locals: {room: Room.new(name: "Room #{Room.count + 1}")} %>

app/views/rooms/edit.html.erb
<% content_for :title, "Editing room" %>

<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

<div id='chatapp'>
  <div id='rooms'>
    <%= button_to session_path, method: :delete, class: 'logout' do %>
        <i class="fa-solid fa-right-from-bracket"></i> Logout
    <% end %>
    <div id='room-list'>
      <%= turbo_stream_from @room.name if @room%>
      <% @rooms.each do |room| %>
        <%= render room %>
      <% end %>
    </div>
    <%= render partial: 'form', locals: {room: Room.new(name: "Room #{Room.count + 1}")} %>
  </div>
  <div id='messages'>
    <%= turbo_frame_tag 'room-messages' do %>
      <div id='message-list'>
        <% @messages.each do |message| %>
        <%= render message %>
        <% end %>
      </div>
      <%= render partial: 'messages/form', locals: {message: Message.new(room: @room)} %>

      <%= turbo_stream_from @room if @room%>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<% content_for :title, "New room" %>

<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>